export enum ERole {
  GUEST = "ROLE_GUEST",
  USER = "ROLE_USER",
  PREMIUM_USER = "ROLE_PREMIUM_USER",
  VIP_USER = "ROLE_VIP_USER",
  MEMBER = "ROLE_MEMBER",
  SUBSCRIBER = "ROLE_SUBSCRIBER",
  CONTRIBUTOR = "ROLE_CONTRIBUTOR",
  AUTHOR = "ROLE_AUTHOR",
  EDITOR = "ROLE_EDITOR",
  REVIEWER = "ROLE_REVIEWER",
  MODERATOR = "ROLE_MODERATOR",
  CURATOR = "ROLE_CURATOR",
  ANALYST = "ROLE_ANALYST",
  SUPPORT_AGENT = "ROLE_SUPPORT_AGENT",
  SUPERVISOR = "ROLE_SUPERVISOR",
  TEAM_LEAD = "ROLE_TEAM_LEAD",
  MANAGER = "ROLE_MANAGER",
  DEPARTMENT_HEAD = "ROLE_DEPARTMENT_HEAD",
  DIRECTOR = "ROLE_DIRECTOR",
  OWNER = "ROLE_OWNER",
  ADMIN = "ROLE_ADMIN",
  SUPER_ADMIN = "ROLE_SUPER_ADMIN",
  SYSTEM = "ROLE_SYSTEM",
  // Domain-specific roles
  FINANCE_MANAGER = "ROLE_FINANCE_MANAGER",
  HR_MANAGER = "ROLE_HR_MANAGER",
  CONTENT_MANAGER = "ROLE_CONTENT_MANAGER",
  MARKETING_MANAGER = "ROLE_MARKETING_MANAGER",
  SALES_MANAGER = "ROLE_SALES_MANAGER",
  PRODUCT_MANAGER = "ROLE_PRODUCT_MANAGER",
  TECHNICAL_LEAD = "ROLE_TECHNICAL_LEAD",
  DEVELOPER = "ROLE_DEVELOPER",
  DESIGNER = "ROLE_DESIGNER",
  TESTER = "ROLE_TESTER",
  DEVOPS = "ROLE_DEVOPS",
  SECURITY_OFFICER = "ROLE_SECURITY_OFFICER",
  COMPLIANCE_OFFICER = "ROLE_COMPLIANCE_OFFICER",
  AUDITOR = "ROLE_AUDITOR",
  // Special purpose roles
  TRIAL_USER = "ROLE_TRIAL_USER",
  SUSPENDED = "ROLE_SUSPENDED",
  BANNED = "ROLE_BANNED",
}

export type RoleType = `${ERole}`;

// biome-ignore lint/suspicious/noExplicitAny: trust me
export type RoleClassType = new (...args: any[]) => IRole;

export interface IRole {
  getRoleLevel: (role: ERole) => number;
  hasRole: (userRole: ERole, requiredRole: ERole) => boolean;
  getInheritedRoles: (role: ERole) => ERole[];
}
