import { defineConfig } from "bunup";
import { copy } from "bunup/plugins";

export default defineConfig({
  entry: [
    "./src/entities/book/index.ts",
    "./src/entities/common/index.ts",
    "./src/entities/folder/index.ts",
    "./src/entities/image/index.ts",
    "./src/entities/payment/index.ts",
    "./src/entities/video/index.ts",
    "./src/entities/user/index.ts",
    "./src/entities/gamification/index.ts",
    "./src/entities/gamification/flashcard/index.ts",
    "./src/entities/gamification/mcq/index.ts",
    "./src/entities/country/index.ts",
    "./src/entities/currency/index.ts",
    "./src/entities/medecine/index.ts",

    "./src/repositories/book/index.ts",
    "./src/repositories/common/index.ts",
    "./src/repositories/image/index.ts",
    "./src/repositories/payment/index.ts",
    "./src/repositories/video/index.ts",
    "./src/repositories/user/index.ts",
    "./src/repositories/gamification/index.ts",
    "./src/repositories/gamification/flashcard/index.ts",
    "./src/repositories/gamification/mcq/index.ts",
    "./src/repositories/country/index.ts",
    "./src/repositories/currency/index.ts",
    "./src/repositories/medecine/index.ts",

    "./src/migrations/book/index.ts",
    "./src/migrations/common/index.ts",
    "./src/migrations/country/index.ts",
    "./src/migrations/currency/index.ts",
    "./src/migrations/folder/index.ts",
    "./src/migrations/gamification/index.ts",
    "./src/migrations/gamification/flashcard/index.ts",
    "./src/migrations/gamification/mcq/index.ts",
    "./src/migrations/image/index.ts",
    "./src/migrations/medecine/index.ts",
    "./src/migrations/payment/index.ts",
    "./src/migrations/user/index.ts",
    "./src/migrations/video/index.ts",
  ],
  target: "bun",
  format: ["esm"],
  drop: ["console", "debugger"],
  packages: "external",
  sourcemap: "external",
  unused: {
    level: "error",
  },
  exports: false,
  minify: true,
  dts: {
    minify: false,
  },
  plugins: [copy(["../../LICENSE"]).to("../")],
});
